name: Test and build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  go-setup:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.3

      - name: Verify Dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run go vet
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Run Tests
        run: go test -race ./...

  backend-docker:
    needs: go-setup
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image for Backend
        run: |
          docker build -t ghcr.io/k5sha/ticketo-backend:latest ./

      - name: Push Docker Image for Backend to GHCR
        run: |
          echo ${{ secrets.MY_GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/k5sha/ticketo-backend:latest

  frontend-docker:
    needs: go-setup
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image for Frontend
        run: |
          docker build -t ghcr.io/k5sha/ticketo-frontend:latest ./web

      - name: Push Docker Image for Frontend to GHCR
        run: |
          echo ${{ secrets.MY_GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/k5sha/ticketo-frontend:latest
